### ISSUE TITLE
usage of exiftool with image data in variable

### ISSUE THREAD

**Issue by mrAceT** [tsmgeek/ExifTool_PHP_Stayopen#11]
Could I use this library for reading exifdata from image date stored in a variable?

I now have this (PHP):

```
    $info = getimagesizefromstring($body,$info2);
    $exif = exif_read_data("data://".$info['mime'].";base64," . base64_encode($body),0,1,1);
```

But I'dd like to have the functionality of exiftool.. field of view and lens id, etc..

If you could supply a small POC I'dd be grateful :D

**Comment by tsmgeek** [comment]
You can not pass binary data to it , but you could write that data out into a tmpfile and then pass the filepath to exiftool to extract all the data you want.

Examples are in the repo https://github.com/tsmgeek/ExifTool_PHP_Stayopen/tree/master/src/examples/gearman
You can just use the parts in the worker and feed it the commands as you need.
Note that its quite slow to use as a single executable because if the time it requires to initialise, hence why I use a background worker.
